/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ia03classificador;

import javax.swing.JOptionPane;

/**
 *
 * @author Paulo Valle
 */
public class jFrClassificador extends javax.swing.JFrame {
    
    private Double v00 = (double)0;
    private Double v01, v02, v03, v04, v05, v06, v07, v08, v09, v10, v11, v13, v14, v15;
    private String name, legs;
    
    /**
     * Creates new form jFrClassificador
     */
    public jFrClassificador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btn00 = new javax.swing.JToggleButton();
        btn01 = new javax.swing.JToggleButton();
        btn02 = new javax.swing.JToggleButton();
        btn03 = new javax.swing.JToggleButton();
        btn04 = new javax.swing.JToggleButton();
        btn05 = new javax.swing.JToggleButton();
        btn06 = new javax.swing.JToggleButton();
        btn07 = new javax.swing.JToggleButton();
        btn08 = new javax.swing.JToggleButton();
        btn09 = new javax.swing.JToggleButton();
        btn10 = new javax.swing.JToggleButton();
        btn11 = new javax.swing.JToggleButton();
        btn13 = new javax.swing.JToggleButton();
        btn14 = new javax.swing.JToggleButton();
        btn15 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        txtLegs = new javax.swing.JTextField();
        lblCassification = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name:");

        txtName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtName.setToolTipText("DIgite o nome");

        btn00.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn00.setText("Hair");
        btn00.setToolTipText("Pelo");
        btn00.setMaximumSize(new java.awt.Dimension(30, 30));
        btn00.setMinimumSize(new java.awt.Dimension(120, 50));
        btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn00ActionPerformed(evt);
            }
        });

        btn01.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn01.setText("Feathers");
        btn01.setToolTipText("Penas");
        btn01.setMaximumSize(new java.awt.Dimension(30, 30));
        btn01.setMinimumSize(new java.awt.Dimension(120, 50));

        btn02.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn02.setText("Eggs");
        btn02.setToolTipText("Ovos");
        btn02.setMaximumSize(new java.awt.Dimension(30, 30));
        btn02.setMinimumSize(new java.awt.Dimension(120, 50));

        btn03.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn03.setText("Milk");
        btn03.setToolTipText("Leite");
        btn03.setMaximumSize(new java.awt.Dimension(30, 30));
        btn03.setMinimumSize(new java.awt.Dimension(120, 50));

        btn04.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn04.setText("Airborne");
        btn04.setToolTipText("Aereo");
        btn04.setMaximumSize(new java.awt.Dimension(30, 30));
        btn04.setMinimumSize(new java.awt.Dimension(120, 50));

        btn05.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn05.setText("Aquatic");
        btn05.setToolTipText("Aquatico");
        btn05.setMaximumSize(new java.awt.Dimension(30, 30));
        btn05.setMinimumSize(new java.awt.Dimension(120, 50));

        btn06.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn06.setText("Predator");
        btn06.setToolTipText("Predador");
        btn06.setMaximumSize(new java.awt.Dimension(30, 30));
        btn06.setMinimumSize(new java.awt.Dimension(120, 50));

        btn07.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn07.setText("Toothed");
        btn07.setToolTipText("Dentes");
        btn07.setMaximumSize(new java.awt.Dimension(30, 30));
        btn07.setMinimumSize(new java.awt.Dimension(120, 50));

        btn08.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn08.setText("Backbone");
        btn08.setToolTipText("Vertebrado");
        btn08.setMaximumSize(new java.awt.Dimension(30, 30));
        btn08.setMinimumSize(new java.awt.Dimension(120, 50));

        btn09.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn09.setText("Breathes");
        btn09.setToolTipText("Respira");
        btn09.setMaximumSize(new java.awt.Dimension(30, 30));
        btn09.setMinimumSize(new java.awt.Dimension(120, 50));

        btn10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn10.setText("Venomous");
        btn10.setToolTipText("Venenoso");
        btn10.setMaximumSize(new java.awt.Dimension(30, 30));
        btn10.setMinimumSize(new java.awt.Dimension(120, 50));

        btn11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn11.setText("Fins");
        btn11.setToolTipText("Barbatanas");
        btn11.setMaximumSize(new java.awt.Dimension(30, 30));
        btn11.setMinimumSize(new java.awt.Dimension(120, 50));

        btn13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn13.setText("Tail");
        btn13.setToolTipText("Rabo");
        btn13.setMaximumSize(new java.awt.Dimension(30, 30));
        btn13.setMinimumSize(new java.awt.Dimension(120, 50));

        btn14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn14.setText("Domestic");
        btn14.setToolTipText("Doméstico");
        btn14.setMaximumSize(new java.awt.Dimension(30, 30));
        btn14.setMinimumSize(new java.awt.Dimension(120, 50));

        btn15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn15.setText("Catsize");
        btn15.setToolTipText("Ágil");
        btn15.setMaximumSize(new java.awt.Dimension(30, 30));
        btn15.setMinimumSize(new java.awt.Dimension(120, 50));

        jLabel2.setText("Legs:");

        txtLegs.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtLegs.setToolTipText("Número de Pernas");
        txtLegs.setMaximumSize(new java.awt.Dimension(150, 50));
        txtLegs.setMinimumSize(new java.awt.Dimension(150, 50));

        lblCassification.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCassification.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCassification.setToolTipText("Classification");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn07, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn08, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtName))
                    .addComponent(txtLegs, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCassification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn07, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn08, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCassification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLegs, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn00ActionPerformed
        if (v00 == (double)0){
            JOptionPane.showMessageDialog(null, "CLICADO");
            v00 = (double)1;
        } else {
            JOptionPane.showMessageDialog(null, "nao clicado");
            v00 = (double)0;
        }
        
    }//GEN-LAST:event_btn00ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrClassificador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrClassificador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrClassificador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrClassificador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrClassificador().setVisible(true);
            }
        });
    }
    
    public void doClassificate(){
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn00;
    private javax.swing.JToggleButton btn01;
    private javax.swing.JToggleButton btn02;
    private javax.swing.JToggleButton btn03;
    private javax.swing.JToggleButton btn04;
    private javax.swing.JToggleButton btn05;
    private javax.swing.JToggleButton btn06;
    private javax.swing.JToggleButton btn07;
    private javax.swing.JToggleButton btn08;
    private javax.swing.JToggleButton btn09;
    private javax.swing.JToggleButton btn10;
    private javax.swing.JToggleButton btn11;
    private javax.swing.JToggleButton btn13;
    private javax.swing.JToggleButton btn14;
    private javax.swing.JToggleButton btn15;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCassification;
    private javax.swing.JTextField txtLegs;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
