/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wekafrontend;

/**
 *
 * @author Marcos Nava
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxPelos = new javax.swing.JCheckBox();
        cbxPenas = new javax.swing.JCheckBox();
        cbbPernas = new javax.swing.JComboBox<>();
        btnClassificar = new javax.swing.JButton();
        txtClassificacao = new javax.swing.JTextField();
        cbxOvos = new javax.swing.JCheckBox();
        cbxLeite = new javax.swing.JCheckBox();
        cbxAereo = new javax.swing.JCheckBox();
        cbxAquatico = new javax.swing.JCheckBox();
        cbxPredador = new javax.swing.JCheckBox();
        cbxDentes = new javax.swing.JCheckBox();
        cbxEspinha = new javax.swing.JCheckBox();
        cbxRespira = new javax.swing.JCheckBox();
        cbxVenenoso = new javax.swing.JCheckBox();
        cbxBarbatana = new javax.swing.JCheckBox();
        cbxRabo = new javax.swing.JCheckBox();
        cbxDomestico = new javax.swing.JCheckBox();
        cbxAgil = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Weka Frontend");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cbxPelos.setText("Tem pelos");
        cbxPelos.setActionCommand("Tem pelos");

        cbxPenas.setText("Tem penas");

        cbbPernas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não tem pernas", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        btnClassificar.setText("Classificar");
        btnClassificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassificarActionPerformed(evt);
            }
        });

        txtClassificacao.setEnabled(false);

        cbxOvos.setText("Põe ovos");

        cbxLeite.setText("Dá leite");

        cbxAereo.setText("Aéreo");

        cbxAquatico.setText("Aquático");

        cbxPredador.setText("Predador");

        cbxDentes.setText("Tem dentes");

        cbxEspinha.setText("Tem espinha");

        cbxRespira.setText("Respira ar");

        cbxVenenoso.setText("É venenoso");

        cbxBarbatana.setText("Tem barbatana");

        cbxRabo.setText("Tem rabo");

        cbxDomestico.setText("É doméstico");

        cbxAgil.setText("É ágil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClassificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxPelos)
                            .addComponent(cbxPenas)
                            .addComponent(cbxOvos)
                            .addComponent(cbxLeite)
                            .addComponent(cbxAereo)
                            .addComponent(cbxAquatico)
                            .addComponent(cbxPredador)
                            .addComponent(cbxDentes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxAgil)
                            .addComponent(cbxDomestico)
                            .addComponent(cbxRabo)
                            .addComponent(cbbPernas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxBarbatana)
                            .addComponent(cbxVenenoso)
                            .addComponent(cbxRespira)
                            .addComponent(cbxEspinha))
                        .addGap(41, 41, 41)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxPelos)
                    .addComponent(cbxEspinha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxPenas)
                    .addComponent(cbxRespira))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxOvos)
                    .addComponent(cbxVenenoso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxLeite)
                    .addComponent(cbxBarbatana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxAereo)
                    .addComponent(cbbPernas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxAquatico)
                    .addComponent(cbxRabo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxPredador)
                    .addComponent(cbxDomestico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxDentes)
                    .addComponent(cbxAgil))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClassificar)
                    .addComponent(txtClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClassificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassificarActionPerformed
        double[] vals = new double[16];
        String resultado = "";
        
        if(cbxPelos.isSelected())
            vals[0] = 1.0;
        if(cbxPenas.isSelected())
            vals[1] = 1.0;
        if(cbxOvos.isSelected())
            vals[2] = 1.0;
        if(cbxLeite.isSelected())
            vals[3] = 1.0;
        if(cbxAereo.isSelected())
            vals[4] = 1.0;
        if(cbxAquatico.isSelected())
            vals[5] = 1.0;
        if(cbxPredador.isSelected())
            vals[6] = 1.0;
        if(cbxDentes.isSelected())
            vals[7] = 1.0;
        if(cbxEspinha.isSelected())
            vals[8] = 1.0;
        if(cbxRespira.isSelected())
            vals[9] = 1.0;
        if(cbxVenenoso.isSelected())
            vals[10] = 1.0;
        if(cbxBarbatana.isSelected())
            vals[11] = 1.0;
        vals[12] = cbbPernas.getSelectedIndex();
        if(cbxRabo.isSelected())
            vals[13] = 1.0;
        if(cbxDomestico.isSelected())
            vals[14] = 1.0;
        if(cbxAgil.isSelected())
            vals[15] = 1.0;
        
        Classificacao classificacao = new Classificacao();
        resultado = classificacao.classificar(vals);
        
        if("".equals(resultado))
            txtClassificacao.setText("Não consegui classificar");
        else
            txtClassificacao.setText(resultado);
    }//GEN-LAST:event_btnClassificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClassificar;
    private javax.swing.JComboBox<String> cbbPernas;
    private javax.swing.JCheckBox cbxAereo;
    private javax.swing.JCheckBox cbxAgil;
    private javax.swing.JCheckBox cbxAquatico;
    private javax.swing.JCheckBox cbxBarbatana;
    private javax.swing.JCheckBox cbxDentes;
    private javax.swing.JCheckBox cbxDomestico;
    private javax.swing.JCheckBox cbxEspinha;
    private javax.swing.JCheckBox cbxLeite;
    private javax.swing.JCheckBox cbxOvos;
    private javax.swing.JCheckBox cbxPelos;
    private javax.swing.JCheckBox cbxPenas;
    private javax.swing.JCheckBox cbxPredador;
    private javax.swing.JCheckBox cbxRabo;
    private javax.swing.JCheckBox cbxRespira;
    private javax.swing.JCheckBox cbxVenenoso;
    private javax.swing.JTextField txtClassificacao;
    // End of variables declaration//GEN-END:variables
}
